# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: craigbruce@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

permalink: /blog/:year/:month/:day/:title.html

# Social/SEO settings
author: Craig Bruce
twitter:
  username: craigbruce
social:
  name: Craig Bruce
  links:
    - https://twitter.com/craigbruce
    - https://www.linkedin.com/in/craigbruce
    - https://github.com/craigbruce
    - https://keybase.io/craigbruce
logo: 
twitter_username: craigbruce
github_username:  craigbruce
webmaster_verifications:
  google: dk7eJRLNv7t-5tJFfOZooRFXkFKc-zQJxw6KggxkJOc

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag