# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Craig Bruce
email: craigbruce@gmail.com
description: >-
  A technical slant on the tools required for the trade. Where my trade is 
  cloud computing, linux system administration, cheminformatics & computational chemistry. 
baseurl: ""
url: "https://craigbruce.me"

permalink: /blog/:year/:month/:day/:title.html

# Social/SEO settings
author: Craig Bruce
twitter:
  username: craigbruce
social:
  name: Craig Bruce
  links:
    - https://twitter.com/craigbruce
    - https://www.linkedin.com/in/craigbruce
    - https://github.com/craigbruce
    - https://keybase.io/craigbruce
logo: 
twitter_username: craigbruce
github_username:  craigbruce
webmaster_verifications:
  google: dk7eJRLNv7t-5tJFfOZooRFXkFKc-zQJxw6KggxkJOc

# Google Analytics
google_analytics: UA-45368132-3

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag