version: 0.2

phases:
  install:
    commands:
      - sudo apt-get install wget
      - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_extended_0.52_Linux-64bit.tar.gz
      - tar -xvzf hugo_extended_0.52_Linux-64bit.tar.gz 
      - ./hugo version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - hugo
  post_build:
    commands:
      - echo Build completed on `date`
