version: 0.2

env:
  variables:
    HUGO_VERSION: "0.91.2"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl git
      - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xvzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz 
      - ./hugo version
  pre_build:
    commands:
      - git clone https://github.com/luizdepra/hugo-coder.git themes/hugo-coder
  build:
    commands:
      - ./hugo
artifacts:
  files:
    - '**/*'
  base-directory: public
