version: 0.2

env:
  variables:
    HUGO_VERSION: "0.52"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl git zip
      - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xvzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz 
      - ./hugo version
#      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#      - python3 get-pip.py
#      - pip install awscli
#      - aws --version
  pre_build:
    commands:
      - git clone https://github.com/luizdepra/hugo-coder.git themes/hugo-coder
  build:
    commands:
      - ./hugo
      - cd public
      - zip -r craigbruceme.zip . 
#      - aws s3 sync --delete --storage-class STANDARD_IA public s3://craigbruce.me
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - craigbruceme.zip
