version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl python3-dev
      - curl -L https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_extended_0.52_Linux-64bit.tar.gz -o hugo_extended_0.52_Linux-64bit.tar.gz
      - tar -xvzf hugo_extended_0.52_Linux-64bit.tar.gz 
      - ./hugo version
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python3 get-pip.py
      - pip install awscli
      - aws --version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./hugo
      - aws s3 sync --delete --storage-class STANDARD_IA public s3://craigbruce.me
  post_build:
    commands:
      - echo Build completed on `date`
