version: 0.2

phases:
  install:
    commands:
      - sudo apt-get install hugo
      - hugo version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
