baseURL = "https://craigbruce.me/"
languageCode = "en"
defaultcontentlanguage = "en"
title = "Craig Bruce"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

disqusShortname = "cheminsilico"

[params]
    author = "Craig Bruce"
    info = "Infrastruture/DevOps/SysAdmin/Cheminformatician"
    description = "Craig Bruce's personal website"
    keywords = "blog,developer,personal,devops,aws,infrastructure,amazon web services"
    avatarurl = "img/me.png"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = "Technical tools of the trade"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/craigbruce"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/craigbruce"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/craigbruce"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
